### ISSUE TITLE
pipeline id shell not to be set by a user

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/UVPlugin-LCatalog#2]
Motivation: 
When a pipeline is exporting from server A to server B then this parameter has to be adjust manually (at server B), because pipeline will have different pipeline id.

**Comment by skrchnavy** [comment]
This plugin is discontinued, updated version doesn't require it.

**Comment by Jan-Marcek** [comment]
Could you provide what the plugin we should use?

**Comment by skrchnavy** [comment]
plugin is not ready, so now we use in ODN this plugin. But new features are not planed here.
